### ISSUE TITLE
Annotations from inherited class not working

### ISSUE THREAD

**Issue by driiftkiing** [zircote/swagger-php#492]
I have upgraded an existing swagger documentation from v2 to v3. Also updated all annotations to the newer version. But it seems like the annotations from the extended class is not working.
Getting following notice on the view:
> Notice: Property "property" doesn't exist in a @OAS\Property(), existing properties: "ref", "schema", "title", "description", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionFormat", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "writeOnly", "xml", "externalDocs", "example", "nullable", "deprecated", "allOf", "anyOf", "oneOf", "not", "additionalProperties", "additionalItems", "contains", "patternProperties", "dependencies", "propertyNames", "const", "x", "_context", "_unmerged" in \Project\Cpe\Entity\AbstractCpe->cpe in /data/project_v4/module/project/Cpe/src/Entity/AbstractCpe.php on line 16 in /data/project_v4/vendor/zircote/swagger-php/src/Logger.php on line 38

I have checked already the code and I have nowhere a property called "property" in use.
Code to reproduce:

```
namespace Project\Cpe\Entity;

use Application\Base\Entity\AbstractEntity;

/**
 * @OAS\Schema(type="object", title="AbstractCpe")
 */
abstract class AbstractCpe extends AbstractEntity
{

    /**
     * @OAS\Property(description="desc", example="cpe-2.2:/o:microsoft:windows_vista")
     *
     * @var string
     */
    protected $cpe = '';
}
```
and:
```
namespace Project\Asset\Entity;

use Project\Cpe\Entity\AbstractCpe;

/**
 * @OAS\Schema(type="object", title="Cpe")
 */
class Cpe extends AbstractCpe
{

    /**
     * @OAS\Property(description="desc", example="1")
     *
     * @var int
     */
    protected $id = - 1;
}
```

Is there any solution to fix this problem?

**Comment by bfanger** [comment]
Should be fixed now, thanks for reporting the bug.

**Comment by fstselic** [comment]
I'm using the latest 3.x-dev branch and still have this issue.

My code looks like this:
```
/**
* @OAS\Schema(type="object", required={"hostname"}, title="Asset")
 */
class Asset extends AbstractEntity
{

    /**
     * @OAS\Property(
     * description="The unique id of the asset.",
     * example=10000,
     * readOnly=true,
     * uniqueItems=true
     * )
     *
     * @var int
     */
    protected $id = - 1;
	
    /**
     * @OAS\Property(
     * description="The hostname can be an IP address or an FQDN.",
     * example="192.168.10.10",
     * uniqueItems=true,
     * readOnly=true
     * )
     *
     * @var string
     */
    protected $hostname = '';
}

/**
 * @OAS\Schema(type="object", required={}, title="Scan Report Asset")
 */
class ScanReportAsset extends Asset
{
    /**
     * @OAS\Property(
     * description="The start date time of the scan of this asset in ISO 8601 format.",
     * example="2005-08-15T15:52:01+0000",
     * readOnly=true,
     * type="string"
     * )
     *
     * @var \DateTime
     */
    protected $start;

    /**
     * @OAS\Property(
     * description="The end date time of the scan of this asset in ISO 8601 format.",
     * example="2005-08-15T15:52:01+0000",
     * readOnly=true,
     * type="string"
     * )
     *
     * @var \DateTime
     */
    protected $end;
}
```
When I navigate to the documentation, the browser is generating the following exception.

`Notice: Property "property" doesn't exist in a @OAS\Property(), existing properties: "ref", "schema", "title", "description", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionFormat", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "writeOnly", "xml", "externalDocs", "example", "nullable", "deprecated", "allOf", "anyOf", "oneOf", "not", "additionalProperties", "additionalItems", "contains", "patternProperties", "dependencies", "propertyNames", "const", "x", "_context", "_unmerged" in \VulnWatcher\Asset\Entity\Asset->id in /data/vulnwatcher_v4/module/VulnWatcher/Asset/src/Entity/Asset.php on line 19 in /data/vulnwatcher_v4/vendor/zircote/swagger-php/src/Logger.php on line 38`

Inserting the property by hand would solve the problem, but that should be done automatically through the extends-statement.

This class is not causing troubles.
```
/**
 * @OAS\Schema(type="object", required={}, title="Scan Report Asset")
 */
class ScanReportAsset extends Asset
{
    /**
     * @OAS\Property(
     * property="id",
     * description="The unique id of the asset.",
     * example=10000,
     * readOnly=true,
     * uniqueItems=true
     * )
     */

    /**
     * @OAS\Property(
     * property="hostname",
     * description="The hostname can be an IP address or an FQDN.",
     * example="192.168.10.10",
     * uniqueItems=true,
     * readOnly=true
     * )
     */
	 
    /**
     * @OAS\Property(
     * description="The start date time of the scan of this asset in ISO 8601 format.",
     * example="2005-08-15T15:52:01+0000",
     * readOnly=true,
     * type="string"
     * )
     *
     * @var \DateTime
     */
    protected $start;

    /**
     * @OAS\Property(
     * description="The end date time of the scan of this asset in ISO 8601 format.",
     * example="2005-08-15T15:52:01+0000",
     * readOnly=true,
     * type="string"
     * )
     *
     * @var \DateTime
     */
    protected $end;
}
```

Please reopen the issue, because it seems not to be solved right now.

**Comment by bfanger** [comment]
@fstselic Could you create PR backporting all fixes from the master branch into the 3.x branch?

**Comment by fstselic** [comment]
@bfanger I'm not sure if I understand you correctly, but I just used the latest 3.x-dev branch, by setting my composer dependency to ^3.

What do you mean with 'PR backporting'?

**Comment by bfanger** [comment]
The commits with fixes and changes in the master branch (2.x) are not yet merged in the 3.x branch
I don't have time available in the near feature to merge those fixes into the 3.x

As you seem to want this to happen,  you could do this work and create a Pull Request (PR)

**Comment by fstselic** [comment]
Ok, thanks for letting me know. I will check, if we can plan this work in one of the next sprints.
